steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'gcr.io/project-id/djangocloud:$SHORT_SHA', '-t', 'gcr.io/project-id/express-ts:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['image', 'push', '--all-tags', 'gcr.io/project-id/djangocloud']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - run
    - deploy
    - --region=asia-southeast1
    - --image=gcr.io/project-id/express-ts:latest
    - --max-instances=1
    - --platform=managed
    - --port=8000
    - --allow-unauthenticated
    - express-ts